### Complete GitHub Actions Workflow

name: Build and Deploy Bicep Template

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            az version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Key Vault
        run: |
          az keyvault create --name myKeyVault --resource-group myResourceGroup --location northeurope

      - name: Build Bicep Template
        run: |
          # Validate the Bicep template
          az bicep build --file main.bicep

      - name: Get ACR credentials
        id: get-acr-credentials
        run: |
          ACR_NAME="PeterAppRegistry"  # Replace with your ACR name
          ACR_CREDENTIALS=$(az acr credential show --name $ACR_NAME --query "{username: username, password: passwords[0].value}" -o json)
          echo "REGISTRY_USERNAME=$(echo $ACR_CREDENTIALS | jq -r .username)" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD=$(echo $ACR_CREDENTIALS | jq -r .password)" >> $GITHUB_ENV

      - name: Retrieve secrets from Key Vault
        id: get-secrets
        run: |
          SECRET_USERNAME=$(az keyvault secret show --name acr-username --vault-name myKeyVault --query value -o tsv)
          SECRET_PASSWORD1=$(az keyvault secret show --name acr-password1 --vault-name myKeyVault --query value -o tsv)
          SECRET_PASSWORD2=$(az keyvault secret show --name acr-password2 --vault-name myKeyVault --query value -o tsv)
          echo "REGISTRY_USERNAME=$SECRET_USERNAME" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD1=$SECRET_PASSWORD1" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD2=$SECRET_PASSWORD2" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            az version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create --resource-group myResourceGroup --template-file main.bicep --parameters acrAdminUserEnabled=true containerRegistryImageName=PeterAppRegistry containerRegistryImageVersion=latest adminCredentialsKeyVaultSecretUserName=$REGISTRY_USERNAME adminCredentialsKeyVaultSecretUserPassword1=$REGISTRY_PASSWORD1 adminCredentialsKeyVaultSecretUserPassword2=$REGISTRY_PASSWORD2
